// This file auto-generated by scripts/map-commits-to-steps.rb
BLAZE_COMMITS = {
  "11": {
    "sha": "10bdbc7434b913c85c156ae6e27fdbea4b2e27bb",
    "message": "Add private task feature, remove the autopublish package"
  },
  "10": {
    "sha": "9a1a392a6e3ed81434c68114dc5f31e418bec308",
    "message": "Move logic into Meteor.methods, remove insecure package"
  },
  "9": {
    "sha": "556826bbf72a3025e5afe00d79de98af4fff86c2",
    "message": "Add users and login; display which user created a task"
  },
  "8": {
    "sha": "a89c298a25d532bd771ae6e6c35d8f579f837670",
    "message": "Add option to hide completed tasks, show incomplete task count"
  },
  "5": {
    "sha": "ea5beb34103e48dbd58848de8455479f4061393e",
    "message": "Make it possible to check off and delete tasks"
  },
  "4": {
    "sha": "40eac55b0a6678d1560a8ff804871b0fae115a22",
    "message": "A form to add tasks, sort to make newest tasks at the top"
  },
  "3": {
    "sha": "519fa970161a46755765b3884c32f435252bc862",
    "message": "Replace the static array with a Collection"
  },
  "2": {
    "sha": "e998be2ddf735d361f560b8d8bf9631b1151fee7",
    "message": "Add templates backed by a static array and all of the CSS"
  },
  "1": {
    "sha": "6d14a8cd5ec233ea6714dce2a5e92560438dcf3c",
    "message": "Run `meteor create`"
  }
}