// This file auto-generated by scripts/map-commits-to-steps.rb
REACT_COMMITS = {
  "11.10": {
    "sha": "aa8e37fa3724552a75f0c6795a80839df3e978e8",
    "message": "Add extra security to methods"
  },
  "11.9": {
    "sha": "d9ae927fab1193fa87b177ffa276859ddccc7ad4",
    "message": "Only publish tasks the current user can see"
  },
  "11.8": {
    "sha": "0c4c3c080b5934afca5d6eee6b15036e0df348f2",
    "message": "Add private className to Task when needed"
  },
  "11.7": {
    "sha": "c7dd2497633a214f2940ac14dddfab0a6239b858",
    "message": "Add private button event handler to Task"
  },
  "11.6": {
    "sha": "dbae4bbbbaf26876cb2757dbe6f9a5c9503df535",
    "message": "Add private button, shown only to owner"
  },
  "11.5": {
    "sha": "ecd603a0f8a8f9f646ebf7a52264fce8ccccefbd",
    "message": "Add a new prop type for Task component"
  },
  "11.4": {
    "sha": "da1e2194308465f9a307c8b69a6b743baf5f680c",
    "message": "Update renderTasks to pass in showPrivateButton"
  },
  "11.3": {
    "sha": "a9299cb9ce21e06ff5de739c483df04e2ba850ff",
    "message": "Add setPrivate method"
  },
  "11.2": {
    "sha": "942c9c66d8de46cfa8f47bc4edb5038a063dfcbb",
    "message": "Add publish to server and subscribe to client"
  },
  "11.1": {
    "sha": "669ec22d48db6e0d305a9ad0dab4ec9be6696b7f",
    "message": "Remove autopublish package"
  },
  "10.4": {
    "sha": "cdf35b47a601eb5df5d5af4027885b820b203b15",
    "message": "Update Task to use setChecked and removeTask methods"
  },
  "10.3": {
    "sha": "8ab8d4a9d7988fbf38e07c0f6b1b9fb1380a2317",
    "message": "Update App component to use addTask method"
  },
  "10.2": {
    "sha": "9a1ed5dc970b163fdeb38191e3c895601bb921e7",
    "message": "Add methods for add, remove, update task"
  },
  "10.1": {
    "sha": "8b6a3d7f7ab2e3972ad0d70bb1b5a049c4d04380",
    "message": "Remove insecure package"
  },
  "9.8": {
    "sha": "d8b57eb7e511cb32bb1d07cc3aed3fc318e0592a",
    "message": "Update Task component to show username"
  },
  "9.7": {
    "sha": "14326f789ec20b89796978a6b20956e9cb4fc4e7",
    "message": "Wrap new task form to only show when logged in"
  },
  "9.6": {
    "sha": "aca9333e69ffdeb31eea7e89a666801d733a8e34",
    "message": "Update getMeteorData to return data about user"
  },
  "9.5": {
    "sha": "2519198dfd053b036463dc6e026484342df47f7e",
    "message": "Update insert to save username and owner"
  },
  "9.4": {
    "sha": "c1c9fd68243fbfbb9fa24a5924c2c4af5c097fa6",
    "message": "Configure accounts-ui to only require username"
  },
  "9.3": {
    "sha": "a5ab9b8f2147dbc77b64c94b5369fb478f20bd92",
    "message": "Include sign in form"
  },
  "9.2": {
    "sha": "3ffdac0480183c849ad8cbbfa8e84079596b6db5",
    "message": "Create Accounts UI wrapper component"
  },
  "9.1": {
    "sha": "b8a8d27d0f2808c18b7160a088ee56772ec29e77",
    "message": "Add accounts-ui and accounts-password packages"
  },
  "8.6": {
    "sha": "f0d790f05e0f3e0466392d97bd6900861100b561",
    "message": "Display incompleteCount in the header"
  },
  "8.5": {
    "sha": "8e56c9854433546590e5ea6173cc74a0456e53eb",
    "message": "Update getMeteorData to return incompleteCount"
  },
  "8.4": {
    "sha": "2364ea342e26daef71c78186d88bcd09aee17483",
    "message": "Replace getMeteorData to filter tasks"
  },
  "8.3": {
    "sha": "37f39a8c2c81d01d3bc438e79cb8edf5dc23391f",
    "message": "Add toggleHideCompleted handler to App"
  },
  "8.2": {
    "sha": "0abf8e9a5745c0ed72fe56547e4b30e67deab5a0",
    "message": "Add getInitialState to App component"
  },
  "8.1": {
    "sha": "0897d01b349735fdeddff6cde09a7f630c976890",
    "message": "Add hide completed checkbox to App component"
  },
  "5.1": {
    "sha": "7fc3e783e846828b0d4a3d9bb7a27e01ce395809",
    "message": "Update Task component to add features"
  },
  "4.3": {
    "sha": "102b5b14357856f2125abf0978fac242bc6f68d4",
    "message": "Update getMeteorData to sort tasks by time"
  },
  "4.2": {
    "sha": "7814c907ba3b19f71222892db8a75d69be15c3c8",
    "message": "Add handleSubmit method to App component"
  },
  "4.1": {
    "sha": "00f681c51a39366c387af94615dbb4d818056178",
    "message": "Add form for new tasks"
  },
  "3.2": {
    "sha": "b96965e36191a6071c279e1e86262be6587909f4",
    "message": "Modify App component to get tasks from collection"
  },
  "3.1": {
    "sha": "2190d7d87b177541bdc28b6011e0282810362bcc",
    "message": "Define tasks collection"
  },
  "2.6": {
    "sha": "e66de095331e3390c2684f5080d7f11e45c7c8fc",
    "message": "Add CSS"
  },
  "2.5": {
    "sha": "197c54dd37419b5bcb9dc045ae4791deaddcbde4",
    "message": "Create Task component"
  },
  "2.4": {
    "sha": "f26af2fb34333dfde00589bb0a65cf38e3cb3390",
    "message": "Create App component"
  },
  "2.3": {
    "sha": "9e8020b66d1fa467b6fb00fc3541f9e0bfae98eb",
    "message": "Replace starter JS"
  },
  "2.2": {
    "sha": "fec7e5aa905b7e0642af3ec1049f9f42d0459265",
    "message": "Replace starter HTML code"
  },
  "2.1": {
    "sha": "e23e1c9902bfc05fd21f709a8c6b0de58f05bb5f",
    "message": "Add the React package"
  },
  "1": {
    "sha": "ec18d9c416ce36418de3c07d40ecdab53ae9fd69",
    "message": "Run `meteor create`"
  }
}